version: "2"
services:
  frontend:
    image: "node:9"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "5678:5678"
    command: bash -c "cd /home/node/app && npm install && npm run dev"
